Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1

Style/Next:
  Enabled: false

Layout/LineLength:
  Max: 180

Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false
